import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { getServerSession } from "next-auth";
import { useState } from "react";

import { api } from "~/utils/api";
import { NextResponse } from "next/server";
import { useRouter } from "next/router";
import Signin from "~/components/Signin";



const Home: NextPage = () => {  
  const router = useRouter()
    const { data: sessionData, status } = useSession();
    if(status === "authenticated"){
      router.push("/dashboard")
    }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#026d17] to-[#152c1e]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Portfolio Project 3
          </h1>
          <div className="flex flex-col items-center gap-2">
            <Signin />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;